apiVersion: v1
kind: Service
metadata:
  name: restapi
  namespace: test
spec:
  selector:
    app: restapi
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080